### PR TITLE
fold: Fix up conversion mode in simplify_conv_narrow

### LINKED ISSUE #37: asm_conv: Assertion `((IRType)((ir->t).irt & IRT_TYPE)) != st' failed.
Hi, I have seen your email in the LuaJIT mail list. It is a good news that you are pushing LuaJIT ahead.

Several days ago, I submitted a bug report to the LuaJIT but no response is given back.
https://github.com/LuaJIT/LuaJIT/issues/524

The bug can be reproduced with the master branch of moonjit, so I think you might feel interested about it.

I have reduced the reproduce script to a few lines:
```lua
local bit = require "bit"
local ffi = require "ffi"

ffi.cdef[[
    typedef unsigned int u32;
]]
local prime = 16777619

local function prepare_hash(s)
    -- change this line to `sq = prime` eliminates the crash
    local sq = ffi.cast("u32", prime)
    local i = #s
    while i > 0 do
        -- crash when LuaJIT try to compile this while block
        sq = ffi.cast("u32", sq * sq)
        i = bit.rshift(i, 1)
    end
end

for case = 1, 1000 do
    prepare_hash("12345678")
end
```

When the `lua_assert(irt_type(ir->t) != st)` failed, `irt_type(ir->t)` is `IRT_INT`.
So maybe something wrong happens when LuaJIT generates an invalid IR `CONV INT to INT`, triggers assertion failure during converting IR to mcode.

### PR DESCRIPTION
**Pull request by siddhesh**
Fixes #37.

simplify_conv_narrow transforms a 64-bit to 32-bit int conversion
after an operation (e.g. add, sub, mul) to an op of the converted
operands by simply converting the operands into 32-bit int.  It
however fails to update the destination type of the conversion mode
because of which one ends up with inconsistent IR and fails with an
assertion.

The test case is incorporated into this patch but it doesn't actually
get executed in the make check.  ffi_convert.lua needs extensive
fixing up to enable it in the testsuite and is currently out of scope
for 2.1.2.

Signed-off-by: Siddhesh Poyarekar <siddhesh@gotplt.org>
Signed-off-by: spacewander <spacewanderlzx@gmail.com>

### CODE REVIEW

File: test/lib/ffi/ffi_convert.lua [hunk 1]
```diff
@@ -769,6 +770,18 @@ do
   x.ppf = ffi.C.strcpy
 end
 
+do
```
Comment (hippi777) [inline test/lib/ffi/ffi_convert.lua:773]: the indentation is really messy (even a tab is there)
otherwise i couldnt really figure out whats the purpose of it, but that can be my fault

Comment (siddhesh) [reply test/lib/ffi/ffi_convert.lua:773]: Thanks for the review.  Fixed with #49 and #50.

Comment (hippi777) [reply test/lib/ffi/ffi_convert.lua:773]: thx for the fix! :D (i try to catch up, so actually i do it whenever i have time for it, but there is still much to discover and understand to become a more valuable reviewer :D )

File: src/lj_opt_fold.c [hunk 2]
```diff
@@ -1260,6 +1260,7 @@ LJFOLDF(simplify_conv_narrow)
   IROp op = (IROp)fleft->o;
   IRType t = irt_type(fins->t);
   IRRef op1 = fleft->op1, op2 = fleft->op2, mode = fins->op2;
+  mode = (IRT_INT << IRCONV_DSH) | (mode & IRCONV_SRCMASK);
```
Comment (mraleph) [inline src/lj_opt_fold.c:1263]: In src/lj_opt_fold.c:

> @@ -1260,6 +1260,7 @@ LJFOLDF(simplify_conv_narrow)
>   IROp op = (IROp)fleft->o;
>   IRType t = irt_type(fins->t);
>   IRRef op1 = fleft->op1, op2 = fleft->op2, mode = fins->op2;
>+  mode = (IRT_INT << IRCONV_DSH) | (mode & IRCONV_SRCMASK);

I think this fix is wrong. Note that you have IR:
```
left src_t ARITH  op1 op2
fins dst_t CONV   left dst_t.src_t
```
and you want to push conversion through arriving to IR
```
op1' dst_t CONV   op1 dst_t.src_t
op2' dst_t CONV   op2 dst_t.src_t 
fins dst_t ARITH  op1' op2'
```
With this fix we end up with IR like this:
```
op1' int CONV   op1 int.src_t
op2' int CONV   op2 int.src_t 
fins dst_t ARITH  op1' op2'
```
which does not seem right at all.

From this it follows that the actual bug is in lines 1264/1265. They should read:
```
op1 = emitir(IRT(IR_CONV, t), op1, mode);
op2 = emitir(IRT(IR_CONV, t), op2, mode);
```
i.e. we need to preserve the type of the conversion we are pushing upwards with respect to its mode - not the other way arround - change the mode to satisfy INT type.

My guess about the origin of the bug would be that first this rule only handled IRCONV_INT_* cases (so using IRTI was correct). Then when it was extended to handle IRCONV_U32_* cases it was missed that emitir should be updated. git blame seems to corroborate this.

If you want I can make a PR fixing this.

Comment (siddhesh) [reply src/lj_opt_fold.c:1263]: [Yikes, I somehow ended up editing your comment instead of replying, sorry about that!]

> My guess about the origin of the bug would be that first this rule only handled `IRCONV_INT_*` cases (so using `IRTI` was correct). Then when it was extended to handle `IRCONV_U32_*` cases it was missed that `emitir` should be updated. `git blame` seems to corroborate this.
>
> If you want I can make a PR fixing this.  

Thanks for digging up the history.  I agree that fixing up the mode to preserve sign is a better idea.  Please make a PR for this.
